name: Extract ZIP

on:
  push:
    paths:
      - "*.zip"

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: List Repository Files
        run: ls -R

      - name: Unzip File
        run: unzip -o Coursera-Django-Menu-Creation-main.zip -d extracted-folder
      
      - name: Commit Extracted Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add extracted-folder/*
          git commit -m "Extracted ZIP contents" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ashwani0506/Django.git HEAD:main


